{
  "hash": "2a483a49eb00d0d831809c1c9f5824e1",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: DATASCI 350 - Data Science Computing\nsubtitle: Lecture 22 - SQL Revision with DuckDB\nauthor:\n  - name: Danilo Freire\n    email: danilo.freire@emory.edu\n    affiliations: \"Department of Data and Decision Sciences <br> Emory University\"\nformat:\n  clean-revealjs:\n    self-contained: false\n    code-overflow: wrap\n    footer: \"[SQL with DuckDB](https://danilofreire.github.io/datasci350/lectures/lecture-22/22-sql-revision.html)\"\ntransition: slide\ntransition-speed: default\nscrollable: true\nengine: python3\nexecute:\n  freeze: auto\n  cache: true\nrevealjs-plugins:\n  - fontawesome\n  - multimodal\neditor:\n  render-on-save: true\n---\n\n# Hello again! 😊 {background-color=\"#1B3A6B\"}\n\n# Brief recap 📚 {background-color=\"#1B3A6B\"}\n\n## Parallel computing fundamentals\n### Where lecture 21 left us\n\n:::{style=\"margin-top: 30px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- Last class we covered [parallel and scalable computing]{.alert}:\n  - [`map`]{.alert}, embarrassingly parallel problems, `joblib` and `concurrent.futures`\n  - [Big O]{.alert}: parallelism cuts the constant, the complexity class stays the same\n  - [Amdahl's law](https://en.wikipedia.org/wiki/Amdahl%27s_law): the serial share caps your speed-up, so measure before scaling\n  - [The GIL](https://en.wikipedia.org/wiki/Global_interpreter_lock): threads for I/O, processes for CPU, C/Rust libraries sidestep it\n  - [Dask]{.alert}: lazy arrays and DataFrames for bigger-than-RAM data\n:::\n\n:::{.column width=\"50%\"}\n- We ended with a promise: some engines [parallelise for you]{.alert}, with no cluster to manage\n- DuckDB is one of them, and today we use it to revise [SQL]{.alert}\n- All queries today run on the [WDI panel]{.alert} you built in the previous lectures\n- [Download the dataset here](https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet) or use the path `../lecture-19/data/wdi_panel.parquet`\n\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/parallel.png){width=\"52%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/parallel.png\"}\n:::\n:::\n:::\n:::\n\n## Lecture overview\n### What we will cover today\n\n:::{style=\"margin-top: 12px; font-size: 21px;\"}\n:::{.columns}\n::::{.column width=\"50%\"}\n[1. Why SQL and why DuckDB]{.alert}\n\n- A declarative language every engine speaks\n- `import duckdb` is the whole setup\n\n[2. First queries]{.alert}\n\n- `SELECT`, `WHERE`, `ORDER BY`, `LIMIT`\n- `IN`, `BETWEEN`, `LIKE`, and the order a query runs in\n\n[3. Aggregating]{.alert}\n\n- `COUNT`, `AVG`, `GROUP BY`, `HAVING`\n- What `COUNT` does when values are missing\n::::\n\n::::{.column width=\"50%\"}\n[4. NULLs, CASE and windows]{.alert}\n\n- `IS NULL`, `COALESCE`, income bands with `CASE`\n- Window functions: a group mean and a rank on every row\n\n[5. Joins]{.alert}\n\n- Primary keys, foreign keys, and the `ON` clause\n- `INNER`, `LEFT`, `FULL OUTER` on two tiny tables\n\n[6. DuckDB and pandas]{.alert}\n\n- Querying a `pandas` DataFrame by its variable name\n- Handing a result back with `.df()`\n- DuckDB on 200 million rows\n::::\n:::\n:::\n\n# Why SQL, why DuckDB 🦆 {background-color=\"#1B3A6B\"}\n\n## Why SQL\n### You describe the answer, the engine finds it\n\n:::{style=\"margin-top: 40px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [SQL](https://en.wikipedia.org/wiki/SQL) is a language for [asking questions of tables]{.alert}\n- It is [relational]{.alert}: tables have rows and columns, and you can combine them with joins\n- It is [declarative]{.alert}: you say what you want, and the engine decides how to compute it\n  - No loops or variable assignments, no input/output code\n  - The engine can reorder the query, read fewer columns, or use every core\n- [SQL is about fifty years old,](https://en.wikipedia.org/wiki/SQL) and data job adverts list it [at least as often as Python](https://finance.yahoo.com/sectors/technology/articles/research-sql-rivals-python-america-131700698.html)\n- Dialects differ in the details, but `SELECT`, `WHERE`, `GROUP BY` and `JOIN` are the same in DuckDB, SQLite, PostgreSQL, BigQuery and Snowflake\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/duckdb-docs-sql-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/duckdb-docs-sql-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nDuckDB's SQL introduction: <https://duckdb.org/docs/stable/sql/introduction>\n:::\n:::\n:::\n:::\n:::\n\n## Why DuckDB for a revision class\n### An in-process engine with no setup\n\n:::{style=\"margin-top: 40px; font-size: 23px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\n- [Zero setup]{.alert}: `pip install duckdb`, then `import duckdb`. [In contrast with PostgreSQL](https://www.postgresql.org/docs/19/admin.html), we don't need a server, a database, a user or a password\n- [In-process]{.alert}: the database runs inside your Python session, [like SQLite](https://www.sqlite.org/) (\"SQLite for analytics\")\n- [Reads files by name]{.alert}: a Parquet or CSV path goes straight in the `FROM` clause\n- Reads a `pandas` DataFrame by its variable name too (more on this later)\n- [Columnar]{.alert} and [parallel]{.alert} underneath, so the same `GROUP BY` works on 200 million rows\n- Version on my laptop: [DuckDB 1.5.5](https://duckdb.org/2026/03/09/announcing-duckdb-150)\n:::\n\n:::{.column width=\"48%\"}\n:::{style=\"text-align: center; margin-top: -10px;\"}\n[![](figures/duckdb-home-2026.png){width=\"100%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/duckdb-home-2026.png\"}\n\n:::{style=\"font-size: 17px;\"}\nSource: <https://duckdb.org>\n:::\n:::\n:::\n:::\n:::\n\n# First queries {background-color=\"#1B3A6B\"}\n\n## What a table is\n### Rows, columns and one value per cell\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- A [table]{.alert} is a grid: every [row]{.alert} is one observation, every [column]{.alert} is one variable\n- Each column has one [type]{.alert}: text (`VARCHAR`), whole numbers (`SMALLINT`), decimals (`DOUBLE`)\n- Every cell holds one value or nothing. Nothing is written `NULL` (more on this later)\n- Our table is the [WDI panel]{.alert}: 217 countries, 8 indicators, 34 years (1990 to 2023)\n- The measurement is always in `value`. The column `indicator` says what it measures\n- So almost every query today starts with `WHERE indicator = '...'`, or it mixes dollars with years of life\n- In pandas terms: a table is a DataFrame, a column is a Series, and there is no index\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"text-align: center; font-size: 18px;\"}\nSix rows of the panel, for Brazil in 2019 and 2020:\n\n| country | iso3 | indicator | year | value |\n|---|---|---|---|---|\n| Brazil | BRA | gdp_per_capita | 2019 | 8771.44 |\n| Brazil | BRA | gdp_per_capita | 2020 | 8435.01 |\n| Brazil | BRA | internet_users_pct | 2019 | 73.91 |\n| Brazil | BRA | internet_users_pct | 2020 | 81.34 |\n| Brazil | BRA | life_expectancy | 2019 | 75.81 |\n| Brazil | BRA | life_expectancy | 2020 | 74.51 |\n:::\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 15px;\"}\nNo two rows share the same `country`, `indicator` and `year`. Those three columns together identify a row, which is the idea behind a [primary key]{.alert} in the joins section\n:::\n:::\n:::\n:::\n\n## Querying a Parquet file\n### The file path goes in the FROM clause\n\n:::{style=\"margin-top: 40px; font-size: 23px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- The WDI panel (Parquet file): 59,024 rows of country, indicator, year and value\n- You can [download it here](https://github.com/danilofreire/datasci350/raw/refs/heads/main/lectures/lecture-19/data/wdi_panel.parquet) or use the path `../lecture-19/data/wdi_panel.parquet`\n- `duckdb.sql()` takes a query string and returns a result you can print\n- The path goes in [single quotes]{.alert}: single quotes mean text, double quotes mean a column name\n- It's not necessary to use `read_parquet`, create a connection or call `fetchall()`. DuckDB does all that for you\n- The [column types]{.alert} under the names come from the Parquet file\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#614845fd .cell cache='true' execution_count=2}\n``` {.python .cell-code}\nimport duckdb\n\nduckdb.sql(\"\"\"\n    SELECT *\n    FROM '../lecture-19/data/wdi_panel.parquet'\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=1}\n```\n┌─────────┬─────────┬────────────────┬───────┬──────────────────┐\n│ country │  iso3   │   indicator    │ year  │      value       │\n│ varchar │ varchar │    varchar     │ int16 │      double      │\n├─────────┼─────────┼────────────────┼───────┼──────────────────┤\n│ Aruba   │ ABW     │ co2_per_capita │  1990 │ 3.20303411789078 │\n│ Aruba   │ ABW     │ co2_per_capita │  1991 │ 3.43571688721622 │\n│ Aruba   │ ABW     │ co2_per_capita │  1992 │  3.6345192377364 │\n│ Aruba   │ ABW     │ co2_per_capita │  1993 │ 3.41453484426953 │\n│ Aruba   │ ABW     │ co2_per_capita │  1994 │ 3.68322701204975 │\n└─────────┴─────────┴────────────────┴───────┴──────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Creating a view\n### One name for the file\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"44%\"}\n- A [view]{.alert} is a saved query that behaves like a table\n- `CREATE OR REPLACE VIEW wdi AS SELECT ...` gives that query the name `wdi`\n- Every later query then says `FROM wdi` and never repeats the file path\n- A view holds no data: DuckDB re-reads the Parquet file on each query\n- `OR REPLACE` overwrites an existing view, so the cell is safe to re-run\n- [`COUNT(DISTINCT country)`]{.alert} counts the different values in a column\n- The panel has 59,024 rows, 217 countries and 8 indicators\n- The view lives in this Python session, so a restart means creating it again\n:::\n\n:::{.column width=\"56%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#01a110cf .cell cache='true' execution_count=3}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE VIEW wdi AS\n    SELECT * FROM '../lecture-19/data/wdi_panel.parquet'\n\"\"\")\n\nduckdb.sql(\"\"\"\n    SELECT COUNT(*) AS n_rows,\n           COUNT(DISTINCT country) AS countries,\n           COUNT(DISTINCT indicator) AS indicators\n    FROM wdi\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=2}\n```\n┌────────┬───────────┬────────────┐\n│ n_rows │ countries │ indicators │\n│ int64  │   int64   │   int64    │\n├────────┼───────────┼────────────┤\n│  59024 │       217 │          8 │\n└────────┴───────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## DESCRIBE and SUMMARIZE\n### Two commands to run before any query\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"44%\"}\n- Run both before writing a query, so you know what the columns are called\n- [`DESCRIBE`]{.alert} lists the columns and their types\n- Five columns here: `country`, `iso3` and `indicator` are `VARCHAR`, `year` is `SMALLINT`, `value` is `DOUBLE`\n- `VARCHAR` is text, so a filter on it needs single quotes\n- [`SUMMARIZE`]{.alert} adds min, max, count and the share of missing values per column\n- Both take a query, so you can point them at any `SELECT`\n- 11.06% of `value` is missing, while `country` and `year` have no holes\n- A `SUMMARIZE` result is itself a table, which is why we `SELECT` from it here\n- The closest pandas pair: `df.dtypes` and `df.describe()`\n:::\n\n:::{.column width=\"56%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#b811e23a .cell cache='true' execution_count=4}\n``` {.python .cell-code}\nduckdb.sql(\"DESCRIBE SELECT * FROM wdi\")\n```\n\n::: {.cell-output .cell-output-display execution_count=3}\n```\n┌─────────────┬─────────────┬─────────┬─────────┬─────────┬─────────┐\n│ column_name │ column_type │  null   │   key   │ default │  extra  │\n│   varchar   │   varchar   │ varchar │ varchar │ varchar │ varchar │\n├─────────────┼─────────────┼─────────┼─────────┼─────────┼─────────┤\n│ country     │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │\n│ iso3        │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │\n│ indicator   │ VARCHAR     │ YES     │ NULL    │ NULL    │ NULL    │\n│ year        │ SMALLINT    │ YES     │ NULL    │ NULL    │ NULL    │\n│ value       │ DOUBLE      │ YES     │ NULL    │ NULL    │ NULL    │\n└─────────────┴─────────────┴─────────┴─────────┴─────────┴─────────┘\n```\n:::\n:::\n\n\n::: {#a3ae9c1c .cell cache='true' execution_count=5}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT column_name, min, max, null_percentage\n    FROM (SUMMARIZE SELECT country, year, value FROM wdi)\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```\n┌─────────────┬─────────────┬──────────────┬─────────────────┐\n│ column_name │     min     │     max      │ null_percentage │\n│   varchar   │   varchar   │   varchar    │  decimal(9,2)   │\n├─────────────┼─────────────┼──────────────┼─────────────────┤\n│ country     │ Afghanistan │ Zimbabwe     │            0.00 │\n│ year        │ 1990        │ 2023         │            0.00 │\n│ value       │ 0.0         │ 1438069596.0 │           11.06 │\n└─────────────┴─────────────┴──────────────┴─────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## SELECT, aliases, ORDER BY, LIMIT\n### Picking columns and sorting the result\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- The whole query is a Python string handed to `duckdb.sql()`\n- SQL keywords are written in upper case by convention, and `select` works just as well\n- Column names are case-insensitive too, so `Country` finds `country`\n- `SELECT` lists the columns you want, and `*` means all of them\n  - It can also compute a new one, as `ROUND(value, 0)` does here\n- [`AS`]{.alert} renames a column in the output, and the new name is an [alias]{.alert}\n- [`ORDER BY value DESC`]{.alert} sorts high to low, and `ASC` is the default\n- [`LIMIT`]{.alert} caps the rows returned, the way `.head()` does in pandas\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#0ee37961 .cell cache='true' execution_count=6}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 0) AS gdp_pc\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND year = 2020\n    ORDER BY value DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```\n┌─────────────┬───────┬──────────┐\n│   country   │ year  │  gdp_pc  │\n│   varchar   │ int16 │  double  │\n├─────────────┼───────┼──────────┤\n│ Monaco      │  2020 │ 161263.0 │\n│ Luxembourg  │  2020 │ 105274.0 │\n│ Bermuda     │  2020 │  98846.0 │\n│ Isle of Man │  2020 │  86595.0 │\n│ Switzerland │  2020 │  86294.0 │\n└─────────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## WHERE with AND, OR and NOT\n### Filtering rows with WHERE\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- [`WHERE`]{.alert} keeps the rows whose condition is true, which is boolean indexing in pandas\n- The comparison operators are `=`, `<>`, `<`, `<=`, `>` and `>=`\n  - One `=` tests equality, and `<>` means \"not equal\"\n- [`AND`]{.alert} needs both sides true, [`OR`]{.alert} needs either one\n- [`NOT`]{.alert} flips a condition: `NOT country = 'Japan'` would keep only Brazil\n- Text goes in single quotes, and the comparison is case-sensitive in DuckDB\n- The brackets matter, because `AND` binds tighter than `OR`\n- Four rows come back: Brazil on 6,818 and 8,435, Japan on 31,779 and 35,363\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#4085a958 .cell cache='true' execution_count=7}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 0) AS gdp_pc\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND (year = 2000 OR year = 2020)\n      AND (country = 'Brazil' OR country = 'Japan')\n    ORDER BY country, year\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=6}\n```\n┌─────────┬───────┬─────────┐\n│ country │ year  │ gdp_pc  │\n│ varchar │ int16 │ double  │\n├─────────┼───────┼─────────┤\n│ Brazil  │  2000 │  6818.0 │\n│ Brazil  │  2020 │  8435.0 │\n│ Japan   │  2000 │ 31779.0 │\n│ Japan   │  2020 │ 35363.0 │\n└─────────┴───────┴─────────┘\n```\n:::\n:::\n\n\n:::\n\n:::{style=\"background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 10px;\"}\nRemove the brackets and the query returns 496 rows. The indicator filter then applies only to the first `OR` branch, so Brazil 2020 comes back with every indicator\n:::\n:::\n:::\n:::\n\n## IN and BETWEEN\n### Shorter ways to write the same conditions\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\n- [`IN`]{.alert} replaces a chain of `OR` comparisons on one column\n- The list goes in brackets, with each text value in single quotes\n- `country IN ('Brazil', 'China')` is the same test as `country = 'Brazil' OR country = 'China'`\n- [`BETWEEN`]{.alert} includes both ends, so 2018 and 2020 covers 2018, 2019 and 2020\n- The low end goes first: `BETWEEN 2020 AND 2018` returns nothing at all\n- pandas writes these two as `.isin([...])` and `.between(2018, 2020)`\n- Six countries over three years give 18 rows, and `LIMIT 6` shows the first six\n- The sort is by country, so those six rows are Brazil and China\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#56d3056c .cell cache='true' execution_count=8}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year,\n           ROUND(value, 0) AS gdp_pc\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year BETWEEN 2018 AND 2020\n    ORDER BY country, year\n    LIMIT 6\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```\n┌─────────┬───────┬─────────┐\n│ country │ year  │ gdp_pc  │\n│ varchar │ int16 │ double  │\n├─────────┼───────┼─────────┤\n│ Brazil  │  2018 │  8722.0 │\n│ Brazil  │  2019 │  8771.0 │\n│ Brazil  │  2020 │  8435.0 │\n│ China   │  2018 │  9799.0 │\n│ China   │  2019 │ 10356.0 │\n│ China   │  2020 │ 10573.0 │\n└─────────┴───────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## LIKE and ILIKE\n### Matching part of a text value\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"44%\"}\n- [`LIKE`]{.alert} matches part of a text value instead of the whole of it\n- `%` stands for any run of characters, including none\n- `_` stands for exactly one character\n- So `'United%'` starts with United, `'%States'` ends with States, and `'%King%'` contains King\n- [`DISTINCT`]{.alert} removes duplicate rows: the view holds one row per country, indicator and year\n- Three countries match: United States, United Arab Emirates and United Kingdom\n- `LIKE` is case-sensitive, so `'united%'` returns zero rows\n- [`ILIKE`]{.alert} runs the same test ignoring case, and finds those same three\n- pandas does this with `.str.startswith()` or `.str.contains()`\n:::\n\n:::{.column width=\"56%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#c3ce927a .cell cache='true' execution_count=9}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT DISTINCT country\n    FROM wdi\n    WHERE country LIKE 'United%'\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```\n┌──────────────────────┐\n│       country        │\n│       varchar        │\n├──────────────────────┤\n│ United States        │\n│ United Arab Emirates │\n│ United Kingdom       │\n└──────────────────────┘\n```\n:::\n:::\n\n\n::: {#6a02d3d4 .cell cache='true' execution_count=10}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT DISTINCT country\n    FROM wdi\n    WHERE country ILIKE 'united%'\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=9}\n```\n┌──────────────────────┐\n│       country        │\n│       varchar        │\n├──────────────────────┤\n│ United States        │\n│ United Arab Emirates │\n│ United Kingdom       │\n└──────────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## One query, one clause at a time\n### Every clause you have met, in one query\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n:::{style=\"text-align: center; font-size: 22px; margin-top: 10px; margin-bottom: 30px;\"}\n| Clause | What it does |\n|---|---|\n| `FROM wdi` | picks the table |\n| `WHERE` | keeps 6 of 59,024 rows |\n| `SELECT` | picks 3 columns, rounds one |\n| `ORDER BY` | sorts by value |\n| `LIMIT` | keeps 3 rows |\n:::\n\n- Every clause here is one you have already met on its own\n- Read a query starting from `FROM`, because that is where the engine starts\n- Three rows survive: the United States on 59,534, Germany on 42,373 and Japan on 35,363\n- We will keep growing this query for the rest of the lecture\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#a1bb2ca6 .cell cache='true' execution_count=11}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year, ROUND(value, 0) AS gdp_pc\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year = 2020\n    ORDER BY value DESC\n    LIMIT 3\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=10}\n```\n┌───────────────┬───────┬─────────┐\n│    country    │ year  │ gdp_pc  │\n│    varchar    │ int16 │ double  │\n├───────────────┼───────┼─────────┤\n│ United States │  2020 │ 59534.0 │\n│ Germany       │  2020 │ 42373.0 │\n│ Japan         │  2020 │ 35363.0 │\n└───────────────┴───────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## The order a query really runs in\n### How the engine evaluates a query\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{style=\"text-align: center;\"}\n[![](figures/sql-evaluation-order.png){width=\"60%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-evaluation-order.png\"}\n:::\n\n:::{.columns}\n:::{.column width=\"50%\"}\n- You write `SELECT` first, but the engine runs it fifth\n- `FROM` finds the rows, `WHERE` filters them, `GROUP BY` forms the groups, `HAVING` filters groups, then `SELECT` computes the output\n- `ORDER BY` sorts what `SELECT` produced, and `LIMIT` runs last of all\n:::\n\n:::{.column width=\"50%\"}\n- An aggregate cannot go in `WHERE`: the groups do not exist yet\n- Standard SQL rejects a `SELECT` alias inside `WHERE`. DuckDB accepts it, but the alias never exists before `SELECT` runs\n- pandas makes you write the steps in this same order: `df[mask].groupby(...).agg(...)`\n:::\n:::\n:::\n\n# Aggregating {background-color=\"#1B3A6B\"}\n\n## GROUP BY {#sec-group-by}\n### One row of output per group\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- An [aggregate function]{.alert} reads many rows and returns one number\n- The five you will use most: `COUNT` how many, `SUM` the total, `AVG` the mean, `MIN` the smallest, `MAX` the largest\n- Without `GROUP BY`, the whole filtered table is one group and you get one row\n- [`GROUP BY country`]{.alert} makes six groups, so the result has six rows\n- Every column in `SELECT` must sit in the `GROUP BY` or inside an aggregate\n  - `SELECT country, value ... GROUP BY country` is an error: the group holds 14 different values and SQL will not pick one for you\n- `n` is 14 for every country, because 2010 to 2023 is 14 years. The same move in pandas: `.groupby(\"country\").agg(...)`\n- Grouping by two columns gives one row per pair: [[Appendix 04]{.button}](#sec-appendix-04)\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#94f788bc .cell cache='true' execution_count=12}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           COUNT(value) AS n,\n           ROUND(AVG(value), 0) AS mean_gdp\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year >= 2010\n    GROUP BY country\n    ORDER BY mean_gdp DESC\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=11}\n```\n┌───────────────┬───────┬──────────┐\n│    country    │   n   │ mean_gdp │\n│    varchar    │ int64 │  double  │\n├───────────────┼───────┼──────────┤\n│ United States │    14 │  58330.0 │\n│ Germany       │    14 │  42448.0 │\n│ Japan         │    14 │  35682.0 │\n│ China         │    14 │   9017.0 │\n│ Brazil        │    14 │   8923.0 │\n│ India         │    14 │   1694.0 │\n└───────────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## WHERE and HAVING\n### Filtering before and after grouping\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- `WHERE` filters rows before grouping. [`HAVING`]{.alert} filters groups after\n- The run order is `WHERE` → `GROUP BY` → `HAVING` → `SELECT` → `ORDER BY`\n- Only `HAVING` can hold an aggregate, because the groups exist by the time it runs\n- \"Which years count?\" is a row question, so it belongs in `WHERE`\n- \"Which countries qualify?\" is a group question, so it belongs in `HAVING`\n- `HAVING AVG(value) > 30000` leaves three countries standing\n- China, Brazil and India drop out on means of 9,017, 8,923 and 1,694\n- `ORDER BY` can name the alias `mean_gdp`, because it runs after `SELECT`\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#ab9b1a00 .cell cache='true' execution_count=13}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           COUNT(value) AS n,\n           ROUND(AVG(value), 0) AS mean_gdp\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year >= 2010\n    GROUP BY country\n    HAVING AVG(value) > 30000\n    ORDER BY mean_gdp DESC\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=12}\n```\n┌───────────────┬───────┬──────────┐\n│    country    │   n   │ mean_gdp │\n│    varchar    │ int64 │  double  │\n├───────────────┼───────┼──────────┤\n│ United States │    14 │  58330.0 │\n│ Germany       │    14 │  42448.0 │\n│ Japan         │    14 │  35682.0 │\n└───────────────┴───────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## COUNT(\\*) and COUNT(value)\n### Counting rows and counting values\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- [`COUNT(*)`]{.alert} counts rows, whatever those rows hold\n- [`COUNT(value)`]{.alert} counts only the rows where `value` is present\n- The gap between the two is the number of holes in the column\n- `AVG`, `SUM`, `MIN` and `MAX` skip missing values without warning you\n- The panel holds 217 country rows in every year\n- 25 values are missing in 1990, 18 in 2000 and 9 in 2020\n- Coverage of GDP per capita [improves]{.alert} over time\n- The pandas version of the same check: `len(df)` against `df[\"value\"].count()`\n- Run this on any column before you trust its mean\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#49820064 .cell cache='true' execution_count=14}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT year,\n           COUNT(*) AS n_rows,\n           COUNT(value) AS with_value,\n           COUNT(*) - COUNT(value) AS missing\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND year IN (1990, 2000, 2020)\n    GROUP BY year\n    ORDER BY year\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=13}\n```\n┌───────┬────────┬────────────┬─────────┐\n│ year  │ n_rows │ with_value │ missing │\n│ int16 │ int64  │   int64    │  int64  │\n├───────┼────────┼────────────┼─────────┤\n│  1990 │    217 │        192 │      25 │\n│  2000 │    217 │        199 │      18 │\n│  2020 │    217 │        208 │       9 │\n└───────┴────────┴────────────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n# NULLs, CASE and windows {background-color=\"#1B3A6B\"}\n\n## Missing values\n### Working with NULL\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"48%\"}\n- A [NULL]{.alert} means \"unknown\", so it is neither zero nor an empty string\n- Any comparison with NULL gives NULL, and NULL is not true: `NULL = NULL` never matches\n- Test with [`IS NULL`]{.alert}, and use [`IS NOT NULL`]{.alert} for the rows that do carry a value\n- [`COALESCE(a, b)`]{.alert} returns `a`, or `b` when `a` is NULL\n- Yemen has a 2020 row with no GDP figure, so it comes back as 0 here\n- Filling with 0 is a choice, and a mean over this filled column would be wrong\n- `COALESCE` fixes a missing value. A missing [row]{.alert} needs a `LEFT JOIN` (joins section)\n- pandas calls the same thing `NaN`, and `.fillna(0)` does this job\n:::\n\n:::{.column width=\"52%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#41d46641 .cell cache='true' execution_count=15}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(COALESCE(value, 0), 0) AS gdp_filled\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND country IN ('Brazil', 'China', 'Germany', 'India',\n                      'Japan', 'United States', 'Yemen, Rep.')\n    ORDER BY country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=14}\n```\n┌───────────────┬────────────┐\n│    country    │ gdp_filled │\n│    varchar    │   double   │\n├───────────────┼────────────┤\n│ Brazil        │     8435.0 │\n│ China         │    10573.0 │\n│ Germany       │    42373.0 │\n│ India         │     1807.0 │\n│ Japan         │    35363.0 │\n│ United States │    59534.0 │\n│ Yemen, Rep.   │        0.0 │\n└───────────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## CASE\n### Writing an if-else ladder inside a SELECT\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- [`CASE`]{.alert} writes an if-else ladder inside a `SELECT`\n- `WHEN` states a condition and `THEN` gives the value to use when it holds\n- The tests run top to bottom, and the first true one wins\n- `ELSE` catches everything left over, and `END` closes the ladder\n- Without `ELSE`, an unmatched row gets NULL\n- The thresholds are the World Bank's income bands: 13,846, 4,466 and 1,136 dollars\n- The `IS NULL` test comes first on purpose. Lower down, Yemen would fall through to `ELSE` and be labelled \"Low income\"\n- The output is a new column you can group by, join on, or export\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#d72c9688 .cell cache='true' execution_count=16}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, ROUND(value, 0) AS gdp_pc,\n        CASE\n            WHEN value IS NULL  THEN 'No data'\n            WHEN value >= 13846 THEN 'High income'\n            WHEN value >= 4466  THEN 'Upper middle'\n            WHEN value >= 1136  THEN 'Lower middle'\n            ELSE 'Low income'\n        END AS income_band\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND country IN ('Brazil', 'China', 'Germany', 'India',\n                      'Japan', 'United States', 'Yemen, Rep.')\n    ORDER BY value DESC NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=15}\n```\n┌───────────────┬─────────┬──────────────┐\n│    country    │ gdp_pc  │ income_band  │\n│    varchar    │ double  │   varchar    │\n├───────────────┼─────────┼──────────────┤\n│ United States │ 59534.0 │ High income  │\n│ Germany       │ 42373.0 │ High income  │\n│ Japan         │ 35363.0 │ High income  │\n│ China         │ 10573.0 │ Upper middle │\n│ Brazil        │  8435.0 │ Upper middle │\n│ India         │  1807.0 │ Lower middle │\n│ Yemen, Rep.   │    NULL │ No data      │\n└───────────────┴─────────┴──────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Window functions {#sec-windows}\n### A group-level number on every row\n\n<style>#sec-windows .cell-output pre code { font-size: 0.8em !important; }</style>\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- `GROUP BY year` would collapse these twelve rows to two\n- A [window function]{.alert} keeps every row and adds a group-level number beside it\n- The [window]{.alert} is the set of rows the function looks at for the current row\n- [`OVER`]{.alert} turns an ordinary aggregate into a window function\n- [`PARTITION BY year`]{.alert} splits the rows into groups, one window per year\n- Partition is the window word for group, and no row leaves the output\n- `year_mean` repeats on every row of its year: 20,885 for 2000 and 26,347 for 2020\n- pandas writes this as `.groupby(\"year\")[\"value\"].transform(\"mean\")`\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#965b07ea .cell cache='true' execution_count=17}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, year, ROUND(value, 0) AS gdp_pc,\n           ROUND(AVG(value) OVER (PARTITION BY year), 0)\n               AS year_mean\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year IN (2000, 2020)\n    ORDER BY year, value DESC\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=16}\n```\n┌───────────────┬───────┬─────────┬───────────┐\n│    country    │ year  │ gdp_pc  │ year_mean │\n│    varchar    │ int16 │ double  │  double   │\n├───────────────┼───────┼─────────┼───────────┤\n│ United States │  2000 │ 48616.0 │   20885.0 │\n│ Germany       │  2000 │ 35104.0 │   20885.0 │\n│ Japan         │  2000 │ 31779.0 │   20885.0 │\n│ Brazil        │  2000 │  6818.0 │   20885.0 │\n│ China         │  2000 │  2237.0 │   20885.0 │\n│ India         │  2000 │   757.0 │   20885.0 │\n│ United States │  2020 │ 59534.0 │   26347.0 │\n│ Germany       │  2020 │ 42373.0 │   26347.0 │\n│ Japan         │  2020 │ 35363.0 │   26347.0 │\n│ China         │  2020 │ 10573.0 │   26347.0 │\n│ Brazil        │  2020 │  8435.0 │   26347.0 │\n│ India         │  2020 │  1807.0 │   26347.0 │\n└───────────────┴───────┴─────────┴───────────┘\n  12 rows                           4 columns\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Ranking with a window\n### RANK() needs an ORDER BY inside OVER\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- [`RANK()`]{.alert} numbers the rows by the `ORDER BY` written inside `OVER`\n- There are two `ORDER BY` clauses here: the inner one decides the ranks, the outer one sorts the printed table\n- No `PARTITION BY` means one window, covering the whole result\n- Ties share a rank and the next rank is skipped, giving 1, 2, 2, 4\n- `DENSE_RANK()` gives 1, 2, 2, 3 instead, and `ROW_NUMBER()` never ties\n- The United States ranks 1 on 59,534 and India ranks 6 on 1,807\n- The ranking covers these six countries only, because `WHERE` runs first\n- Add `PARTITION BY year` to rank within each year separately\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#0db95ed0 .cell cache='true' execution_count=18}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, ROUND(value, 0) AS gdp_pc,\n           RANK() OVER (ORDER BY value DESC) AS rank_2020\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita'\n      AND country IN ('Brazil', 'China', 'Germany',\n                      'India', 'Japan', 'United States')\n      AND year = 2020\n    ORDER BY rank_2020\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=17}\n```\n┌───────────────┬─────────┬───────────┐\n│    country    │ gdp_pc  │ rank_2020 │\n│    varchar    │ double  │   int64   │\n├───────────────┼─────────┼───────────┤\n│ United States │ 59534.0 │         1 │\n│ Germany       │ 42373.0 │         2 │\n│ Japan         │ 35363.0 │         3 │\n│ China         │ 10573.0 │         4 │\n│ Brazil        │  8435.0 │         5 │\n│ India         │  1807.0 │         6 │\n└───────────────┴─────────┴───────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n# Joins {background-color=\"#1B3A6B\"}\n\n## Two small tables\n### Keys, and the two tables we will join\n\n<style>#two-small-tables .cell-output pre code { font-size: 0.8em !important; }</style>\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"42%\"}\n- A [table]{.alert} is a grid with named columns and one type per column\n- `CREATE TABLE ... AS SELECT` builds one from a query, as `gdp2020` is built here\n- `CREATE TABLE (col TYPE, ...)` declares empty columns, and `INSERT INTO ... VALUES` adds the rows\n- A table stores its data, so it differs from the `wdi` view\n- A [primary key]{.alert} identifies a row uniquely, with no duplicates and no NULLs: `iso3` in `regions`\n- A [foreign key]{.alert} points at another table's primary key: `iso3` in `gdp2020`, and a join follows that link with `ON g.iso3 = r.iso3`\n- Six rows on each side, with two mismatches: [`JPN`]{.alert} has a GDP figure and no region, [`KOR`]{.alert} a region and no GDP figure\n- East Asia holds two codes, which matters in the exercise\n:::\n\n:::{.column width=\"58%\"}\n:::{style=\"font-size: 19px;\"}\n\n::: {#8f9458bb .cell cache='true' execution_count=19}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE TABLE gdp2020 AS\n    SELECT country, iso3, ROUND(value, 0) AS gdp_per_capita\n    FROM wdi\n    WHERE indicator = 'gdp_per_capita' AND year = 2020\n      AND iso3 IN ('USA','BRA','CHN','IND','DEU','JPN')\n\"\"\")\n\nduckdb.sql(\"\"\"\n    CREATE OR REPLACE TABLE regions\n        (iso3 VARCHAR PRIMARY KEY, region VARCHAR)\n\"\"\")\n\nduckdb.sql(\"\"\"\n    INSERT INTO regions VALUES\n        ('USA', 'North America'), ('BRA', 'Latin America'),\n        ('CHN', 'East Asia'),     ('IND', 'South Asia'),\n        ('DEU', 'Europe'),        ('KOR', 'East Asia')\n\"\"\")\n\nduckdb.sql(\"SELECT * FROM regions ORDER BY iso3\")\n```\n\n::: {.cell-output .cell-output-display execution_count=18}\n```\n┌─────────┬───────────────┐\n│  iso3   │    region     │\n│ varchar │    varchar    │\n├─────────┼───────────────┤\n│ BRA     │ Latin America │\n│ CHN     │ East Asia     │\n│ DEU     │ Europe        │\n│ IND     │ South Asia    │\n│ KOR     │ East Asia     │\n│ USA     │ North America │\n└─────────┴───────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Reading a join\n### The ON clause and table aliases\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\n- A [`JOIN`]{.alert} combines two tables into one wider result\n- [`ON`]{.alert} says which columns must agree: `iso3` on both sides\n- Rows pair up when their `iso3` values match, and each pair becomes one output row\n- `AS g` and `AS r` are [table aliases]{.alert}, short names for the two tables\n- `g.country` means \"the `country` column from `gdp2020`\"\n- Prefix every column in `SELECT`, so DuckDB knows which table it came from\n- The join type goes in front of the word `JOIN`, and `INNER` is the default\n- pandas writes the same thing as `pd.merge(gdp2020, regions, on=\"iso3\")`\n- The next three slides run this query with three join types\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 20px;\"}\n```sql\nSELECT g.country, r.region, g.gdp_per_capita\nFROM gdp2020 AS g\nINNER JOIN regions AS r ON g.iso3 = r.iso3\nORDER BY g.country\n```\n:::\n:::\n:::\n:::\n\n## INNER JOIN\n### Only the rows that match on both sides\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\n- An [`INNER JOIN`]{.alert} keeps only the codes present in both tables\n- Six rows on the left, six on the right, [five]{.alert} rows out\n- Japan drops out: `JPN` sits in `gdp2020` and appears nowhere in `regions`\n- Korea drops out too: `KOR` has a region and no 2020 GDP row\n- The five survivors are Brazil, China, Germany, India and the United States\n- An inner join is a silent filter, and nothing warns you about the two lost rows\n- If your row count falls after a join, this is usually why\n- pandas does the same with `pd.merge(..., how=\"inner\")`\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#7e2bb56b .cell cache='true' execution_count=20}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    INNER JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY g.country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=19}\n```\n┌───────────────┬───────────────┬────────────────┐\n│    country    │    region     │ gdp_per_capita │\n│    varchar    │    varchar    │     double     │\n├───────────────┼───────────────┼────────────────┤\n│ Brazil        │ Latin America │         8435.0 │\n│ China         │ East Asia     │        10573.0 │\n│ Germany       │ Europe        │        42373.0 │\n│ India         │ South Asia    │         1807.0 │\n│ United States │ North America │        59534.0 │\n└───────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## LEFT JOIN\n### Keeping every row of the left table\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\n- A [`LEFT JOIN`]{.alert} keeps every row of the left table, matched or not\n- `LEFT` means the table named in `FROM`, which is `gdp2020` here\n- [Six]{.alert} rows now: Japan is back, with `NULL` in `region`\n- The NULL means the join found no partner, and Japan's 35,363 is untouched\n- Korea is still missing, because it exists only in the right table\n- Swap the two tables and you get a different answer, which is what the exercise asks for\n- The join you will reach for most often: add labels without losing rows\n- pandas writes it as `pd.merge(..., how=\"left\")`\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#c1f87fdd .cell cache='true' execution_count=21}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    LEFT JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY g.country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=20}\n```\n┌───────────────┬───────────────┬────────────────┐\n│    country    │    region     │ gdp_per_capita │\n│    varchar    │    varchar    │     double     │\n├───────────────┼───────────────┼────────────────┤\n│ Brazil        │ Latin America │         8435.0 │\n│ China         │ East Asia     │        10573.0 │\n│ Germany       │ Europe        │        42373.0 │\n│ India         │ South Asia    │         1807.0 │\n│ Japan         │ NULL          │        35363.0 │\n│ United States │ North America │        59534.0 │\n└───────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## FULL OUTER JOIN\n### Every row from both tables survives\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- A [`FULL OUTER JOIN`]{.alert} keeps every row from both tables, with NULLs on the side that had no partner\n- [Seven]{.alert} rows: five matched pairs, plus Korea and Japan\n- Korea's row carries a region and NULL for `country` and `gdp_per_capita`\n- Japan's row carries a country and 35,363, and NULL for both region columns\n- On these two tables: 5 rows from `INNER`, 6 from `LEFT`, 7 from `FULL OUTER`\n- To choose a join, ask which table must survive whole\n- Then ask what should happen to the rows with no partner\n\n:::{style=\"text-align: center; margin-top: 10px;\"}\n[![](figures/sql-joins.png){width=\"56%\"}](#){data-modal-type=\"image\" data-modal-url=\"figures/sql-joins.png\"}\n\n:::{style=\"font-size: 15px;\"}\nThe picture uses cut-down tables, so its counts are 3, 4 and 5. Ours give 5, 6 and 7\n:::\n:::\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#608f4635 .cell cache='true' execution_count=22}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, r.iso3 AS region_iso3,\n           r.region, g.gdp_per_capita\n    FROM gdp2020 AS g\n    FULL OUTER JOIN regions AS r ON g.iso3 = r.iso3\n    ORDER BY r.region NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=21}\n```\n┌───────────────┬─────────────┬───────────────┬────────────────┐\n│    country    │ region_iso3 │    region     │ gdp_per_capita │\n│    varchar    │   varchar   │    varchar    │     double     │\n├───────────────┼─────────────┼───────────────┼────────────────┤\n│ China         │ CHN         │ East Asia     │        10573.0 │\n│ NULL          │ KOR         │ East Asia     │           NULL │\n│ Germany       │ DEU         │ Europe        │        42373.0 │\n│ Brazil        │ BRA         │ Latin America │         8435.0 │\n│ United States │ USA         │ North America │        59534.0 │\n│ India         │ IND         │ South Asia    │         1807.0 │\n│ Japan         │ NULL        │ NULL          │        35363.0 │\n└───────────────┴─────────────┴───────────────┴────────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Try it yourself! 🧠 {#sec-exercise-01}\n### Ten minutes\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"52%\"}\nHow rich is each region, and how much data is it based on?\n\n1. Use the `gdp2020` and `regions` tables from the joins section\n2. Report one row per region\n3. Count how many of that region's countries have a 2020 GDP figure\n4. Compute the mean GDP per capita of that region\n5. Keep every region, including the one with no GDP data at all\n6. Sort by mean GDP, highest first\n7. Send the region with no data to the bottom of the list\n:::\n\n:::{.column width=\"48%\"}\nWhat to look for:\n\n- Which table goes on the left if every region must survive?\n- East Asia holds two codes and one GDP figure, so `COUNT(*)` and `COUNT(g.country)` differ\n- Five regions come back, each with a count of 1\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;\"}\nSolution: [[Appendix 01]{.button}](#sec-appendix-01)\n:::\n:::\n:::\n:::\n\n# DuckDB and pandas 🐼 {background-color=\"#1B3A6B\"}\n\n## Querying a DataFrame by name\n### Your Python variable becomes a SQL table\n\n:::{style=\"margin-top: 40px; font-size: 22px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- DuckDB finds `df` among your Python variables and queries it by name\n- There is no registration step, no copy and no conversion to another format\n- It reads the DataFrame where it already sits in memory\n- The same `SELECT` works whether `FROM` names a file, a view or a DataFrame\n- `SELECT COUNT(*) FROM df` returns 59,024, the same count as the Parquet file\n- Any DataFrame in scope will do, so you can join two of them in one query\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#e07e7483 .cell cache='true' execution_count=23}\n``` {.python .cell-code}\nimport pandas as pd\n\ndf = pd.read_parquet(\n    \"../lecture-19/data/wdi_panel.parquet\"\n)\n\nduckdb.sql(\"SELECT COUNT(*) AS n FROM df\")\n```\n\n::: {.cell-output .cell-output-display execution_count=22}\n```\n┌───────┐\n│   n   │\n│ int64 │\n├───────┤\n│ 59024 │\n└───────┘\n```\n:::\n:::\n\n\n:::\n\n:::{style=\"background: rgba(230, 57, 70, 0.1); padding: 12px; border-radius: 10px; font-size: 18px; margin-top: 8px;\"}\n`country` is a pandas category, which DuckDB reads as an [enum]{.alert}. Add `::VARCHAR` when you want plain text in the result\n:::\n:::\n:::\n:::\n\n## Handing the result back to pandas {#sec-pandas}\n### Turning a result into a DataFrame\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"45%\"}\n- [`.df()`]{.alert} turns a DuckDB result into a pandas DataFrame\n- `.pl()` gives a Polars DataFrame and `.arrow()` an Arrow table\n- Without `.df()`, you get a DuckDB relation that prints as a text table\n- `country::VARCHAR` casts the pandas category back to plain text\n- 18 rows come out of SQL, and `pivot` reshapes them into 6 rows by 3 columns\n- `pivot` has no short SQL equivalent, so this is a good place to hand over\n- Everything after `.df()` is ordinary pandas: `.plot()`, `.to_csv()`, `seaborn`, `statsmodels`\n- When to reach for SQL and when to stay in pandas: [[Appendix 06]{.button}](#sec-appendix-06)\n:::\n\n:::{.column width=\"55%\"}\n:::{style=\"font-size: 21px;\"}\n\n::: {#364bfb93 .cell cache='true' execution_count=24}\n``` {.python .cell-code}\nlong = duckdb.sql(\"\"\"\n    SELECT country::VARCHAR AS country, indicator,\n           ROUND(value, 1) AS value\n    FROM df\n    WHERE year = 2020\n      AND iso3 IN ('USA', 'BRA', 'CHN',\n                   'IND', 'DEU', 'JPN')\n      AND indicator IN ('gdp_per_capita',\n                        'life_expectancy',\n                        'internet_users_pct')\n\"\"\").df()\n\nlong.pivot(index=\"country\", columns=\"indicator\",\n           values=\"value\")\n```\n\n::: {.cell-output .cell-output-display execution_count=23}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>indicator</th>\n      <th>gdp_per_capita</th>\n      <th>internet_users_pct</th>\n      <th>life_expectancy</th>\n    </tr>\n    <tr>\n      <th>country</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>Brazil</th>\n      <td>8435.0</td>\n      <td>81.3</td>\n      <td>74.5</td>\n    </tr>\n    <tr>\n      <th>China</th>\n      <td>10573.4</td>\n      <td>70.1</td>\n      <td>78.0</td>\n    </tr>\n    <tr>\n      <th>Germany</th>\n      <td>42372.9</td>\n      <td>89.8</td>\n      <td>81.0</td>\n    </tr>\n    <tr>\n      <th>India</th>\n      <td>1806.5</td>\n      <td>43.4</td>\n      <td>70.2</td>\n    </tr>\n    <tr>\n      <th>Japan</th>\n      <td>35363.3</td>\n      <td>90.2</td>\n      <td>84.6</td>\n    </tr>\n    <tr>\n      <th>United States</th>\n      <td>59533.6</td>\n      <td>90.3</td>\n      <td>77.0</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## DuckDB on 200 million rows {#sec-benchmark}\n### The lecture 21 benchmark, revisited\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"55%\"}\n:::{style=\"text-align: center;\"}\n\n::: {#5647f7a6 .cell cache='true' execution_count=25}\n\n::: {.cell-output .cell-output-display}\n![](22-sql-revision_files/figure-revealjs/cell-25-output-1.png){width=662 height=392}\n:::\n:::\n\n\n:::\n:::\n\n:::{.column width=\"45%\"}\n:::{style=\"font-size: 18px;\"}\n- Task: mean `value` by indicator and decade since 1990, on `wdi_big.parquet`, a synthetic panel of [200,681,600 rows]{.alert}\n- [DuckDB]{.alert}: 0.53 s. [Dask]{.alert}: 5.39 s. [pandas]{.alert}: 9.65 s\n- pandas loads every column into RAM. DuckDB reads only the row groups and columns the query names\n- Why: columnar layout, vectorised execution, all cores by default, and [predicate pushdown]{.alert} into the Parquet file\n- MacBook Pro, Apple M5, 10 cores, 24 GB RAM, macOS 26.6\n- One task on one machine: your seconds will differ, the ranking usually holds\n- [Polars]{.alert} is in the same range as DuckDB (see Tutorial 07 on the course website)\n- The query and the scripts behind it: [[Appendix 07]{.button}](#sec-appendix-07)\n:::\n:::\n:::\n:::\n\n# Summary {background-color=\"#1B3A6B\"}\n\n## What we learned today\n### The vocabulary, in the order we met it\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [SQL]{.alert} is declarative: you describe the answer and the engine plans the work\n- [DuckDB]{.alert} needs one import and reads a Parquet file or a pandas DataFrame by name\n- A [view]{.alert} names a query. `DESCRIBE` and `SUMMARIZE` show what is in it\n- [`WHERE`]{.alert} filters rows, [`GROUP BY`]{.alert} forms groups, [`HAVING`]{.alert} filters groups. No aggregate in `WHERE`\n- `COUNT(*)` minus `COUNT(value)` is the number of missing values\n:::\n\n:::{.column width=\"50%\"}\n- A [NULL]{.alert} means unknown. `COALESCE` fills one in, and a missing row needs a join instead\n- [`CASE`]{.alert} builds a category column from an if-else ladder\n- A [window function]{.alert} keeps every row: `AVG ... OVER (PARTITION BY year)` adds the year mean, `RANK()` a position\n- Joins: 5 rows from `INNER`, 6 from `LEFT`, 7 from `FULL OUTER` on the same two tables\n- On 200 million rows, DuckDB runs the same query in [0.53 seconds]{.alert}\n:::\n:::\n:::\n\n## Next class {#sec-next-class}\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- [Lecture 23]{.alert}: dependency management, virtual environments and containers\n- Today's queries depended on your Python, your DuckDB version and your laptop\n- Next class we package all three into an [image]{.alert} that a classmate, a server or a marker can run and get the same answer\n- `pip install duckdb` stops being a setup instruction and becomes a line in a `Dockerfile`\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"margin-top: -15px;\"}\nBefore then:\n\n1. Finish the join exercise if you did not complete it in class\n2. Work through [Tutorial 04](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html), the DuckDB SQL tutorial on the course website\n3. Check that `import duckdb` works in your environment\n4. More practice with `GROUP BY` and `HAVING`: [[Appendix 02]{.button}](#sec-appendix-02). Common error messages: [[Appendix 03]{.button}](#sec-appendix-03)\n:::\n:::\n:::\n:::\n\n# Thank you very much! 😊 {background-color=\"#1B3A6B\"}\n\n# Appendix 📚 {background-color=\"#1B3A6B\"}\n\n## Appendix 01: Solution to the exercise {#sec-appendix-01}\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\n- `regions` goes on the left because every region must survive\n- East Asia has two rows in `regions` but `COUNT(g.country)` is 1, because Korea's unmatched row holds a NULL\n- `COUNT(*)` would count that empty row and report 2\n- `NULLS LAST` sends the region with no GDP data to the bottom\n- Five regions come back, from North America on 59,534 down to South Asia on 1,807\n- Want the codes that appear in only one table? See [[Appendix 05]{.button}](#sec-appendix-05)\n\n[[Back to the exercise]{.button}](#sec-exercise-01)\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#bcb92553 .cell cache='true' execution_count=26}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT r.region,\n           COUNT(g.country) AS countries_with_gdp,\n           ROUND(AVG(g.gdp_per_capita), 0) AS mean_gdp\n    FROM regions AS r\n    LEFT JOIN gdp2020 AS g ON g.iso3 = r.iso3\n    GROUP BY r.region\n    ORDER BY mean_gdp DESC NULLS LAST\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=25}\n```\n┌───────────────┬────────────────────┬──────────┐\n│    region     │ countries_with_gdp │ mean_gdp │\n│    varchar    │       int64        │  double  │\n├───────────────┼────────────────────┼──────────┤\n│ North America │                  1 │  59534.0 │\n│ Europe        │                  1 │  42373.0 │\n│ East Asia     │                  1 │  10573.0 │\n│ Latin America │                  1 │   8435.0 │\n│ South Asia    │                  1 │   1807.0 │\n└───────────────┴────────────────────┴──────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n:::\n\n## Appendix 02: Practice at home: GROUP BY and HAVING {#sec-appendix-02}\n### One more question to try on your own\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"46%\"}\nWhich countries have had the highest life expectancy since 2010?\n\n1. Create the `wdi` view over the panel\n2. Keep only the `life_expectancy` rows\n3. Keep only the years from 2010 onwards\n4. Compute the mean of `value` for each country\n5. Keep the countries whose mean is above 82\n6. Sort from highest to lowest\n7. Return the top five, rounded to one decimal\n:::\n\n:::{.column width=\"54%\"}\n:::{style=\"font-size: 20px;\"}\n\n::: {#a549dc98 .cell cache='true' execution_count=27}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country,\n           ROUND(AVG(value), 1) AS mean_life_exp\n    FROM wdi\n    WHERE indicator = 'life_expectancy'\n      AND year >= 2010\n    GROUP BY country\n    HAVING AVG(value) > 82\n    ORDER BY mean_life_exp DESC\n    LIMIT 5\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=26}\n```\n┌──────────────────────┬───────────────┐\n│       country        │ mean_life_exp │\n│       varchar        │    double     │\n├──────────────────────┼───────────────┤\n│ Monaco               │          85.5 │\n│ San Marino           │          84.4 │\n│ Hong Kong SAR, China │          84.3 │\n│ Andorra              │          83.8 │\n│ Japan                │          83.8 │\n└──────────────────────┴───────────────┘\n```\n:::\n:::\n\n\n:::\n\n- `WHERE` drops rows, `HAVING AVG(value) > 82` tests the group\n- `ORDER BY` names `mean_life_exp`, the alias created in `SELECT`\n- Japan is the only country in the top five with more than a million people\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to Next class]{.button}](#sec-next-class)\n:::\n:::\n## Appendix 03: When something goes wrong {#sec-appendix-03}\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n[`Parser Error: syntax error at or near \"..\"`]{.alert}\n\nThe file path is not quoted. Put single quotes around it: `FROM '../data/f.parquet'`.\n\n[`IO Error: No files found that match the pattern`]{.alert}\n\nThe path is quoted but wrong. Paths are relative to the folder you launched Python in, so check with `os.getcwd()`.\n\n[`Binder Error: Referenced column \"gdp\" not found`]{.alert}\n\nThe column name is misspelled or does not exist. Run `DESCRIBE SELECT * FROM wdi` and read the list\n:::\n\n:::{.column width=\"50%\"}\n[`Parser Error: syntax error at or near \"SELCT\"`]{.alert}\n\nA keyword is misspelled. DuckDB quotes the offending word back at you, so read the message to the end.\n\n[`Binder Error` on a value you know exists]{.alert}\n\nYou wrote `WHERE indicator = \"gdp_per_capita\"` with double quotes. Double quotes mean a column name in SQL, single quotes mean text.\n\n[`Catalog Error: Table with name wdi does not exist`]{.alert}\n\nThe view lives in the session that created it. Re-run the `CREATE VIEW` cell after restarting Python\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to Next class]{.button}](#sec-next-class)\n:::\n:::\n\n## Appendix 04: Grouping by two columns {#sec-appendix-04}\n### Every combination that exists in the data\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- Name two columns and you get one row for each pair that appears in the filtered rows\n- Two countries and two indicators give four rows here\n- Combinations with no rows never appear. SQL does not invent empty groups\n- Japan's mean life expectancy since 2010 is nine years above Brazil's. Its CO2 per person is almost four times higher\n- Aggregating a mean of yearly means like this weights every year equally. Say so when you report it\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#313f6282 .cell cache='true' execution_count=28}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, indicator,\n           ROUND(AVG(value), 1) AS mean_value\n    FROM wdi\n    WHERE year >= 2010\n      AND country IN ('Brazil', 'Japan')\n      AND indicator IN ('life_expectancy',\n                        'co2_per_capita')\n    GROUP BY country, indicator\n    ORDER BY country, indicator\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=27}\n```\n┌─────────┬─────────────────┬────────────┐\n│ country │    indicator    │ mean_value │\n│ varchar │     varchar     │   double   │\n├─────────┼─────────────────┼────────────┤\n│ Brazil  │ co2_per_capita  │        2.4 │\n│ Brazil  │ life_expectancy │       74.8 │\n│ Japan   │ co2_per_capita  │        9.3 │\n│ Japan   │ life_expectancy │       83.8 │\n└─────────┴─────────────────┴────────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to GROUP BY]{.button}](#sec-group-by)\n:::\n:::\n\n## Appendix 05: Anti-joins and UNION {#sec-appendix-05}\n### Finding rows with no partner\n\n:::{style=\"margin-top: 40px; font-size: 19px;\"}\n:::{.columns}\n:::{.column width=\"44%\"}\n- An [anti-join]{.alert} asks which rows on the left have no partner on the right\n- `NOT EXISTS` runs a small query for each row and keeps the row when it returns nothing\n- Japan is the only such row here, because `JPN` is missing from `regions`\n- A join adds columns. [`UNION`]{.alert} stacks rows from two results that have the same columns\n- `UNION` removes duplicate rows, `UNION ALL` keeps them and is faster\n- The tagged result has five rows: Germany, Japan and the United States rich, Brazil and India poor\n- China falls in neither band, so it appears in no row at all\n:::\n\n:::{.column width=\"56%\"}\n:::{style=\"font-size: 19px;\"}\n\n::: {#4e1680d8 .cell cache='true' execution_count=29}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT g.country, g.iso3\n    FROM gdp2020 AS g\n    WHERE NOT EXISTS (\n        SELECT 1 FROM regions AS r\n        WHERE r.iso3 = g.iso3\n    )\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=28}\n```\n┌─────────┬─────────┐\n│ country │  iso3   │\n│ varchar │ varchar │\n├─────────┼─────────┤\n│ Japan   │ JPN     │\n└─────────┴─────────┘\n```\n:::\n:::\n\n\n::: {#eaced881 .cell cache='true' execution_count=30}\n``` {.python .cell-code}\nduckdb.sql(\"\"\"\n    SELECT country, 'rich' AS tag FROM gdp2020\n    WHERE gdp_per_capita > 30000\n    UNION\n    SELECT country, 'poor' AS tag FROM gdp2020\n    WHERE gdp_per_capita < 10000\n    ORDER BY country\n\"\"\")\n```\n\n::: {.cell-output .cell-output-display execution_count=29}\n```\n┌───────────────┬─────────┐\n│    country    │   tag   │\n│    varchar    │ varchar │\n├───────────────┼─────────┤\n│ Brazil        │ poor    │\n│ Germany       │ rich    │\n│ India         │ poor    │\n│ Japan         │ rich    │\n│ United States │ rich    │\n└───────────────┴─────────┘\n```\n:::\n:::\n\n\n:::\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to the exercise solution]{.button}](#sec-appendix-01)\n:::\n:::\n\n## Appendix 06: When SQL beats a DataFrame {#sec-appendix-06}\n### A checklist for each tool\n\n:::{style=\"margin-top: 40px; font-size: 21px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\nReach for SQL when:\n\n- You are joining two or more tables\n- You are filtering and aggregating a file that is larger than your RAM\n- The question is a `GROUP BY` with a couple of conditions\n- Someone else has to read the query. A colleague who has never seen pandas can still read your `SELECT`\n- The data already lives in a database\n:::\n\n:::{.column width=\"50%\"}\nStay in pandas when:\n\n- You need row-by-row logic that has no set-based version\n- You are plotting, or feeding a model\n- You want many small inspectable steps, each one a variable you can look at\n- The reshaping is the hard part, as in the `pivot` in the DuckDB and pandas section\n\n:::{style=\"background: rgba(27, 58, 107, 0.08); padding: 12px; border-radius: 10px; font-size: 19px; margin-top: 12px;\"}\nWant more practice? The course website has a full self-study [DuckDB SQL tutorial](https://danilofreire.github.io/datasci350/04-duckdb-sql-tutorial.html) covering everything on these slides in more depth\n:::\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to the pandas slide]{.button}](#sec-pandas)\n:::\n:::\n\n## Appendix 07: The benchmark query {#sec-appendix-07}\n### The query and where the timings come from\n\n:::{style=\"margin-top: 40px; font-size: 20px;\"}\n:::{.columns}\n:::{.column width=\"50%\"}\n- The DuckDB version is the query you already know, with a file path in `FROM` and a `GROUP BY` at the end\n- The data is `wdi_big.parquet`, a synthetic panel of 200,681,600 rows built by cloning the small panel many times\n- The file is not committed, and the script that rebuilds it is in [`data/make_big_parquet.py`](https://github.com/danilofreire/datasci350/blob/main/lectures/lecture-22/data/make_big_parquet.py)\n- The timings were measured once and saved to [`data/benchmark_results.csv`](https://raw.githubusercontent.com/danilofreire/datasci350/main/lectures/lecture-22/data/benchmark_results.csv). The deck reads that file rather than re-running anything\n- pandas loads the whole thing and calls `groupby`, Dask uses a parallel DataFrame, and DuckDB runs SQL straight over the file\n:::\n\n:::{.column width=\"50%\"}\n:::{style=\"font-size: 22px;\"}\n\n::: {#a0077764 .cell execution_count=31}\n``` {.python .cell-code}\nimport duckdb\n\nduckdb.sql(\"\"\"\n    SELECT indicator,\n           (year // 10) * 10 AS decade,\n           AVG(value) AS mean_value\n    FROM 'data/wdi_big.parquet'\n    WHERE year >= 1990\n    GROUP BY indicator, decade\n\"\"\").df()\n```\n:::\n\n\n:::\n:::\n:::\n\n:::{style=\"text-align: center; margin-top: 15px;\"}\n[[Back to the benchmark]{.button}](#sec-benchmark)\n:::\n:::\n\n",
    "supporting": [
      "22-sql-revision_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js\" integrity=\"sha384-c9c+LnTbwQ3aujuU7ULEPVvgLs+Fn6fJUvIGTsuu1ZcCf11fiEubah0ttpca4ntM sha384-6V1/AdqZRWk1KAlWbKBlGhN7VG4iE/yAZcO6NZPMF8od0vukrvr0tg4qY6NSrItx\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.min.js\" integrity=\"sha384-ZvpUoO/+PpLXR1lu4jmpXWu80pZlYUAfxl5NsBMWOEPSjUn/6Z/hRTt8+pR6L4N2\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}